---
title: "Analyse der Framingham Heart Study (Patrick)"
---

# Libraries laden

```{r}
#| warning: false
library(tidyverse)
library(dplyr)
library(mosaic)
```

# Framingham-Daten

[Beschreibung des Datensatzes](https://search.r-project.org/CRAN/refmans/riskCommunicator/html/framingham.html)

```
RANDID

    Unique identification number for each participant. Values range from 2448-999312.
SEX

    Participant sex. 1 = Male (n = 5022), 2 = Female (n = 6605).
TOTCHOL

    Serum Total Cholesterol (mg/dL). Values range from 107-696.
AGE

    Age at exam (years). Values range from 32-81.
SYSBP

    Systolic Blood Pressure (mean of last two of three measurements) (mmHg). Values range from 83.5-295.
DIABP

    Diastolic Blood Pressure (mean of last two of three measurements) (mmHg). Values range from 30-150.
CURSMOKE

    Current cigarette smoking at exam. 0 = Not current smoker (n = 6598), 1 = Current smoker (n = 5029).
CIGPDAY

    Number of cigarettes smoked each day. 0 = Not current smoker. Values range from 0-90 cigarettes per day.
BMI

    Body Mass Index, weight in kilograms/height meters squared. Values range from 14.43-56.8.
DIABETES

    Diabetic according to criteria of first exam treated or first exam with casual glucose of 200 mg/dL or more. 0 = Not a diabetic (n = 11097), 1 = Diabetic (n = 530)
BPMEDS

    Use of Anti-hypertensive medication at exam. 0 = Not currently used (n = 10090), 1 = Current use (n = 944).
HEARTRTE

    Heart rate (Ventricular rate) in beats/min. Values range from 37-220.
GLUCOSE

    Casual serum glucose (mg/dL). Values range from 39-478.
educ
PREVCHD

    Prevalent Coronary Heart Disease defined as pre-existing Angina Pectoris, Myocardial Infarction (hospitalized, silent or unrecognized), or Coronary Insufficiency (unstable angina). 0 = Free of disease (n = 10785), 1 = Prevalent disease (n = 842).
PREVAP

    Prevalent Angina Pectoris at exam. 0 = Free of disease (n = 11000), 1 = Prevalent disease (n = 627).
PREVMI

    Prevalent Myocardial Infarction. 0 = Free of disease (n = 11253), 1 = Prevalent disease (n = 374).
PREVSTRK

    Prevalent Stroke. 0 = Free of disease (n = 11475), 1 = Prevalent disease (n = 152).
PREVHYP

    Prevalent Hypertensive. Subject was defined as hypertensive if treated or if second exam at which mean systolic was >=140 mmHg or mean Diastolic >=90 mmHg. 0 = Free of disease (n = 6283), 1 = Prevalent disease (n = 5344).
TIME

    Number of days since baseline exam. Values range from 0-4854
PERIOD

    Examination Cycle. 1 = Period 1 (n = 4434), 2 = Period 2 (n = 3930), 3 = Period 3 (n = 3263)
HDLC

    High Density Lipoprotein Cholesterol (mg/dL). Available for Period 3 only. Values range from 10-189.
LDLC

    Low Density Lipoprotein Cholesterol (mg/dL). Available for Period 3 only. Values range from 20-565.
DEATH

    Death from any cause. 0 = Did not occur during followup, 1 = Did occur during followup.
ANGINA

    Angina Pectoris. 0 = Did not occur during followup, 1 = Did occur during followup.
HOSPMI

    Hospitalized Myocardial Infarction. 0 = Did not occur during followup, 1 = Did occur during followup.
MI_FCHD

    Hospitalized Myocardial Infarction or Fatal Coronary Heart Disease. 0 = Did not occur during followup, 1 = Did occur during followup.
ANYCHD

    Angina Pectoris, Myocardial infarction (Hospitalized and silent or unrecognized), Coronary Insufficiency (Unstable Angina), or Fatal Coronary Heart Disease. 0 = Did not occur during followup, 1 = Did occur during followup.
STROKE

    Atherothrombotic infarction, Cerebral Embolism, Intracerebral Hemorrhage, or Subarachnoid Hemorrhage or Fatal Cerebrovascular Disease. 0 = Did not occur during followup, 1 = Did occur during followup.
CVD

    Myocardial infarction (Hospitalized and silent or unrecognized), Fatal Coronary Heart Disease, Atherothrombotic infarction, Cerebral Embolism, Intracerebral Hemorrhage, or Subarachnoid Hemorrhage or Fatal Cerebrovascular Disease. 0 = Did not occur during followup, 1 = Did occur during followup.
HYPERTEN

    Hypertensive. Defined as the first exam treated for high blood pressure or second exam in which either Systolic is 6 140 mmHg or Diastolic 6 90mmHg. 0 = Did not occur during followup, 1 = Did occur during followup.
TIMEAP

    Number of days from Baseline exam to first Angina during the followup or Number of days from Baseline to censor date. Censor date may be end of followup, death or last known contact date if subject is lost to followup.
TIMEMI

    Number of days from Baseline exam to first HOSPMI event during followup or Number of days from Baseline to censor date. Censor date may be end of followup, death or last known contact date if subject is lost to followup.
TIMEMIFC

    Number of days from Baseline exam to first MI_FCHD event during followup or Number of days from Baseline to censor date. Censor date may be end of followup, death or last known contact date if subject is lost to followup.
TIMECHD

    Number of days from Baseline exam to first ANYCHD event during followup or Number of days from Baseline to censor date. Censor date may be end of followup, death or last known contact date if subject is lost to followup.
TIMESTRK

    Number of days from Baseline exam to first STROKE event during followup or Number of days from Baseline to censor date. Censor date may be end of followup, death or last known contact date if subject is lost to followup.
TIMECVD

    Number of days from Baseline exam to first CVD event during followup or Number of days from Baseline to censor date. Censor date may be end of followup, death or last known contact date if subject is lost to followup.
TIMEDTH

    Number of days from Baseline exam to death if occurring during followup or Number of days from Baseline to censor date. Censor date may be end of followup, or last known contact date if subject is lost to followup.
TIMEHYP

    Number of days from Baseline exam to first HYPERTEN event during followup or Number of days from Baseline to censor date. Censor date may be end of followup, death or last known contact date if subject is lost to followup.
```

Daten liegen in `ext.csv`. Naiv laden:

```{r}
fram <- read_csv(
  "ext.csv"
)
```

*Problem*: Gibt direkt mal eine ominöse Ausgabe. R erklärt alle Attribute zu Strings (=chr). Doof.

*Lösung*: Spaltentypen explizit definieren.


```{r}
fram <- read_csv2(
  "ext.csv",
  col_types = list(
    RANDID = col_integer(),
    SEX = col_factor(),
    TOTCHOL = col_integer(),
    AGE = col_integer(),
    SYSBP = col_number(),
    DIABP = col_number(),
    CURSMOKE = col_logical(),
    CIGPDAY = col_integer(),
    BMI = col_number(),
    DIABETES = col_logical(),
    BPMEDS = col_logical(),
    HEARTRTE = col_integer(),
    GLUCOSE = col_integer(),
    EDUC = col_factor(ordered = TRUE),
    PREVCHD = col_logical(),
    PREVAP = col_logical(),
    PREVMI = col_logical(),
    PREVSTRK = col_logical(),
    PREVHYP = col_logical(),
    TIME = col_integer(),
    PERIOD = col_factor(ordered = TRUE),
    HDLC = col_integer(),
    LDLC = col_integer(),
    DEATH = col_logical(),
    ANGINA = col_logical(),
    HOSPMI = col_logical(),
    MI_FCHD = col_logical(),
    ANYCHD = col_logical(),
    STROKE = col_logical(),
    CVD = col_logical(),
    HYPERTEN = col_logical(),
    TIMEAP = col_integer(),
    TIMEMI = col_integer(),
    TIMEMIFC = col_integer(),
    TIMECHD = col_integer(),
    TIMESTRK = col_integer(),
    TIMECVD = col_integer(),
    TIMEDTH = col_integer(),
    TIMEHYP = col_integer()
  )
)
fram
problems(fram)
```


# Korrelationsanalyse

```{r}
library(GGally)
fram2 <- fram |>
  select(SEX:PREVHYP, HDLC:HYPERTEN)
fram2
#ggpairs(fram2)
```

